# Generated by Django 2.1.7 on 2019-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='photo',
            field=models.TextField(default=''),
        ),
    ]
